package com.cyanchill.missingcore.metadataretriever.model

data class TrackMetadataItem(
  override var bitrate: Int?,
  override var channelCount: Int?,
  override var codecs: String?,
  override var sampleMimeType: String?,
  override var sampleRate: Int?,
  override var albumArtist: String?,
  override var albumTitle: String?,
  override var artist: String?,
  override var artworkData: String?,
  override var artworkDataType: String?,
  override var artworkUri: String?,
  override var compilation: String?,
  override var composer: String?,
  override var conductor: String?,
  override var description: String?,
  override var discNumber: Int?,
  override var displayTitle: String?,
  override var genre: String?,
  override var isBrowsable: Boolean?,
  override var isPlayable: Boolean?,
  override var mediaType: String?,
  override var overallRating: Double?,
  override var recordingDay: Int?,
  override var recordingMonth: Int?,
  override var recordingYear: Int?,
  override var releaseDay: Int?,
  override var releaseMonth: Int?,
  override var releaseYear: Int?,
  override var station: String?,
  override var subtitle: String?,
  override var title: String?,
  override var totalDiscCount: Int?,
  override var totalTrackCount: Int?,
  override var trackNumber: Int?,
  override var userRating: Double?,
  override var writer: String?,
  override var year: Int?,
): MetadataItem
