package com.cyanchill.missingcore.metadataretriever.model

data class TrackMetadataItem(
  override var bitrate: number?,
  override var channelCount: number?,
  override var codecs: string?,
  override var sampleMimeType: string?,
  override var sampleRate: number?,
  override var albumArtist: string?,
  override var albumTitle: string?,
  override var artist: string?,
  override var artworkData: string?,
  override var artworkDataType: string?,
  override var artworkUri: string?,
  override var compilation: string?,
  override var composer: string?,
  override var conductor: string?,
  override var description: string?,
  override var discNumber: number?,
  override var displayTitle: string?,
  override var genre: string?,
  override var isBrowsable: boolean?,
  override var isPlayable: boolean?,
  override var mediaType: string?,
  override var overallRating: number?,
  override var recordingDay: number?,
  override var recordingMonth: number?,
  override var recordingYear: number?,
  override var releaseDay: number?,
  override var releaseMonth: number?,
  override var releaseYear: number?,
  override var station: string?,
  override var subtitle: string?,
  override var title: string?,
  override var totalDiscCount: number?,
  override var totalTrackCount: number?,
  override var trackNumber: number?,
  override var userRating: number?,
  override var writer: string?,
  override var year: number?,
): MetadataItem
